import React from 'react';
import { Salad, Dumbbell, Stethoscope, Sparkles, Bot } from 'lucide-react';

interface Props {
  diet: string;
  exercise: string;
  medical_guidance: string;
  powered_by?: string;
}

export default function RecommendationCards({ diet, exercise, medical_guidance, powered_by }: Props) {
  const isAI = powered_by?.includes('Gemini') || powered_by?.includes('Agent');

  const cards = [
    {
      icon:   <Salad size={22} className="text-green-600" />,
      title:  'Diet Plan',
      text:   diet,
      bg:     'bg-green-50',
      border: 'border-green-200',
    },
    {
      icon:   <Dumbbell size={22} className="text-blue-600" />,
      title:  'Exercise Plan',
      text:   exercise,
      bg:     'bg-blue-50',
      border: 'border-blue-200',
    },
    {
      icon:   <Stethoscope size={22} className="text-purple-600" />,
      title:  'Medical Guidance',
      text:   medical_guidance,
      bg:     'bg-purple-50',
      border: 'border-purple-200',
    },
  ];

  return (
    <div className="space-y-4">
      {/* AI Badge */}
      {powered_by && (
        <div className={`flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium w-fit
          ${isAI
            ? 'bg-indigo-50 text-indigo-700 border border-indigo-200'
            : 'bg-gray-100 text-gray-600 border border-gray-200'
          }`}>
          {isAI ? <Sparkles size={15} /> : <Bot size={15} />}
          {isAI
            ? `Personalised by Dr. AI Assistant (${powered_by})`
            : `Generated by ${powered_by}`
          }
        </div>
      )}

      {/* Recommendation Cards */}
      {cards.map(({ icon, title, text, bg, border }) => (
        <div key={title} className={`rounded-xl border ${border} ${bg} p-5`}>
          <div className="flex items-center gap-2 mb-3">
            {icon}
            <h4 className="font-semibold text-gray-800">{title}</h4>
          </div>
          <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">{text}</p>
        </div>
      ))}

      <p className="text-xs text-gray-400 mt-2 italic">
        These recommendations are AI-generated for informational purposes only.
        Always consult a qualified medical professional before making health decisions.
      </p>
    </div>
  );
}
