import React from 'react';
import { Sparkles, Brain } from 'lucide-react';

interface Props {
  explanation: string;
  riskLevel: string;
}

export default function RiskExplanation({ explanation, riskLevel }: Props) {
  const borderColor =
    riskLevel.includes('HIGH')         ? 'border-red-200'
    : riskLevel.includes('INTERMEDIARY') ? 'border-amber-200'
    : 'border-green-200';

  const bgColor =
    riskLevel.includes('HIGH')         ? 'bg-red-50'
    : riskLevel.includes('INTERMEDIARY') ? 'bg-amber-50'
    : 'bg-green-50';

  return (
    <div className={`rounded-2xl border-2 ${borderColor} ${bgColor} p-6`}>
      {/* Header */}
      <div className="flex items-center gap-2 mb-4">
        <div className="bg-indigo-600 text-white p-1.5 rounded-lg">
          <Brain size={18} />
        </div>
        <div>
          <h3 className="font-semibold text-gray-900 text-base">
            Why do you have this risk score?
          </h3>
          <div className="flex items-center gap-1 text-xs text-indigo-600 font-medium mt-0.5">
            <Sparkles size={12} />
            AI-generated explanation based on your SHAP analysis
          </div>
        </div>
      </div>

      {/* Explanation text */}
      <div className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
        {explanation}
      </div>

      <p className="text-xs text-gray-400 mt-4 italic">
        This explanation is generated by AI based on the model's SHAP feature analysis.
        It reflects the factors that most influenced your risk score.
      </p>
    </div>
  );
}
